kind: pipeline
name: default

steps:
- name: modules
  image: golang:1.12
  commands:
  - go mod download
- name: generate
  image: golang:1.12
  commands:
  - go generate ./...
- name: test
  image: golang:1.12
  commands:
  - go test -v ./...
- name: build
  image: golang:1.12
  commands:
  - mkdir build
  - go build -o build/epubtool ./epubtool
  - go build -o build/epubtool-novalidate -tags novalidate ./epubtool
  - ls -lah build
